
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ELCOT
 */
public class currency extends javax.swing.JFrame {

    /**
     * Creates new form currency
     */
    public currency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        to = new javax.swing.JComboBox<>();
        from = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        convert = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        convert1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jLabel3.setText("CURRENCY CONVERTER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 50, 320, 29);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("FROM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 200, 110, 28);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("TO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 290, 60, 28);

        to.setBackground(new java.awt.Color(0, 0, 0));
        to.setFont(new java.awt.Font("Bodoni MT Black", 3, 14)); // NOI18N
        to.setForeground(new java.awt.Color(153, 153, 153));
        to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIA", "SRILANKA", "BANGLADESH", "NEPAL" }));
        getContentPane().add(to);
        to.setBounds(240, 290, 150, 30);

        from.setBackground(new java.awt.Color(0, 0, 0));
        from.setFont(new java.awt.Font("Bodoni MT Black", 3, 14)); // NOI18N
        from.setForeground(new java.awt.Color(153, 153, 153));
        from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AMERICA", "INDIA", "ENGLAND", "CHINA" }));
        getContentPane().add(from);
        from.setBounds(240, 200, 150, 30);

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("ENTER THE AMOUNT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 240, 22);

        amount.setFont(new java.awt.Font("Bodoni MT Black", 3, 12)); // NOI18N
        getContentPane().add(amount);
        amount.setBounds(250, 112, 190, 40);

        convert.setBackground(new java.awt.Color(0, 0, 0));
        convert.setFont(new java.awt.Font("Bodoni MT Black", 3, 18)); // NOI18N
        convert.setForeground(new java.awt.Color(204, 204, 255));
        convert.setText("CONVERT");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });
        getContentPane().add(convert);
        convert.setBounds(150, 400, 160, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ELCOT\\Documents\\image-657x510.jpg.png")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 450, 520);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ELCOT\\Documents\\IMG-20230927-WA0002.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(457, 0, 150, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ELCOT\\Documents\\IMG-20230927-WA0001.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 110, 150, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ELCOT\\Documents\\IMG-20230927-WA0000.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 220, 130, 80);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ELCOT\\Documents\\image-200x104.jpg.png")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 300, 140, 110);

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(270, 480, 111, 23);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 470, 75, 23);

        convert1.setBackground(new java.awt.Color(0, 0, 0));
        convert1.setFont(new java.awt.Font("Bodoni MT Black", 3, 18)); // NOI18N
        convert1.setForeground(new java.awt.Color(204, 204, 255));
        convert1.setText("CONVERT");
        convert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert1ActionPerformed(evt);
            }
        });
        getContentPane().add(convert1);
        convert1.setBounds(150, 410, 160, 29);

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Bodoni MT Black", 3, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(490, 464, 90, 40);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ELCOT\\Pictures\\image-200x104.jpg.png")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(460, 410, 140, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int num1;
double total;
    private void convert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convert1ActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        num1=Integer.parseInt(amount.getText());

        if(from.getSelectedItem().toString()=="AMERICA"&&to.getSelectedItem().toString()=="INDIA"){
            total=num1*83.17;
            JOptionPane.showMessageDialog(null, "USD TO INR");}
        else if(from.getSelectedItem().toString()=="AMERICA"&&to.getSelectedItem().toString()=="SRILANKA")
        { total=num1*325.18;
            JOptionPane.showMessageDialog(null, "USD TO SL RUPPE");}
        else if(from.getSelectedItem().toString()=="AMERICA"&&to.getSelectedItem().toString()=="BANGLADESH")
        { total=num1*110.64;
            JOptionPane.showMessageDialog(null, "USD TO TAKKA");}
        else if(from.getSelectedItem().toString()=="AMERICA"&&to.getSelectedItem().toString()=="NEPAL")
        {total=num1*133.58;
            JOptionPane.showMessageDialog(null, "USD TO NEPAL RUPPE");
        }
        else if(from.getSelectedItem().toString()=="INDIA"&&to.getSelectedItem().toString()=="SRILANKA")
        { total=num1*3.91;
            JOptionPane.showMessageDialog(null, "INR TO SL RUPEE");
        }
        else if(from.getSelectedItem().toString()=="INDIA"&&to.getSelectedItem().toString()=="BANGLADESH")
        { total=num1*1.33;
            JOptionPane.showMessageDialog(null, "INR TO TAKKA");
        }
        else if(from.getSelectedItem().toString()=="INDIA"&&to.getSelectedItem().toString()=="NEPAL")
        { total=num1*1.61;
            JOptionPane.showMessageDialog(null, "INR TO NEPALRUPEE");
        }
        else if(from.getSelectedItem().toString()=="ENGLAND"&&to.getSelectedItem().toString()=="INDIA")
        {total=num1*101.07;
            JOptionPane.showMessageDialog(null, "POUNDS TO INR");
        }
        else if(from.getSelectedItem().toString()=="ENGLAND"&&to.getSelectedItem().toString()=="SRILANKA")
        { total=num1*394.97;
            JOptionPane.showMessageDialog(null, "POUNDS TO SL RUPEE");
        }
        else if(from.getSelectedItem().toString()=="ENGLAND"&&to.getSelectedItem().toString()=="BANGLADESH")
        {total=num1*134.38;
            JOptionPane.showMessageDialog(null, "POUNDS TO TAKKA");
        }
        else if(from.getSelectedItem().toString()=="ENGLAND"&&to.getSelectedItem().toString()=="NEPAL")
        { total=num1*162.28;
            JOptionPane.showMessageDialog(null, "POUNDS TO NEPAL RUPEE");
        }
        else if(from.getSelectedItem().toString()=="CHINA"&&to.getSelectedItem().toString()=="INDIA")
        { total=num1*11.48;
            JOptionPane.showMessageDialog(null, "YUAN TO INR");
        }
        else if(from.getSelectedItem().toString()=="CHINA"&&to.getSelectedItem().toString()=="SRILANKA")
        {total=num1*44.51;
            JOptionPane.showMessageDialog(null, "YUAN TO SL RUPEE");
        }

        else if(from.getSelectedItem().toString()=="CHINA"&&to.getSelectedItem().toString()=="BANGLADESH")
        { total=num1*15.15;
            JOptionPane.showMessageDialog(null, "YUAN TO TAKKA");
        }
        else
        { total=num1*18.29;
            JOptionPane.showMessageDialog(null, "YUAN TO NEPAL RUPEE");
        }

        amount.setText(total+"");

    }//GEN-LAST:event_convertActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        amount.setText("");
        num1=(0);
        total=(0);
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JButton clear;
    private javax.swing.JButton convert;
    private javax.swing.JButton convert1;
    private javax.swing.JComboBox<String> from;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> to;
    // End of variables declaration//GEN-END:variables
}
